# Build the LilithWindowCapture C++ proxy winmm.dll.
#
# Usage:
#   .\make.ps1                 # build; output winmm.dll to repo root
#   .\make.ps1 -Build          # same, explicit
#   .\make.ps1 -Clean          # clean obj/ and make.log
#   .\make.ps1 -Vcvars "path"  # specify vcvars64.bat manually
#
# The C++ proxy forwards winmm native exports to C:\Windows\System32\winmm.dll
# (falls back to SysWOW64), no bundled winmm_orig.dll required. It permanently
# creates a transparent, click-through proxy window so window-capture tools can
# enumerate the desktop pet. Logs go to LilithWindowCapture.log in game root.

param(
    [switch]$Build,
    [switch]$Clean,
    [string]$Vcvars
)

$ErrorActionPreference = 'Stop'

$root    = $PSScriptRoot
$srcDir  = Join-Path $root 'src'
$objDir  = Join-Path $root 'obj'
$cppTarget = Join-Path $root 'winmm.dll'

# --- 0. read version (single source: version.txt), generate src/version.h ---
$versionFile = Join-Path $root 'version.txt'
if (-not (Test-Path $versionFile)) {
    throw "version.txt not found: $versionFile"
}
$version = (Get-Content $versionFile -Raw).Trim()
if ($version -notmatch '^\d+\.\d+\.\d+$') {
    throw "version.txt must be like 1.0.0, got: '$version'"
}
Write-Host "=== version: $version ===" -ForegroundColor Cyan

$versionH = Join-Path $srcDir 'version.h'
$versionHContent = @"
#pragma once

// AUTO-GENERATED by make.ps1 from version.txt - do not edit by hand.
#define LILITHWINDOWCAPTURE_VERSION_MAJOR $($version.Split('.')[0])
#define LILITHWINDOWCAPTURE_VERSION_MINOR $($version.Split('.')[1])
#define LILITHWINDOWCAPTURE_VERSION_PATCH $($version.Split('.')[2])
#define LILITHWINDOWCAPTURE_VERSION_WSTR L"$version"
"@
Set-Content -Path $versionH -Value $versionHContent -Encoding UTF8
Write-Host "generated: $versionH"

# --- clean mode ---
if ($Clean) {
    if (Test-Path $objDir) {
        Remove-Item -Recurse -Force $objDir
        Write-Host "cleaned: $objDir"
    } else {
        Write-Host 'nothing to clean.'
    }
    $logFile = Join-Path $root 'make.log'
    if (Test-Path $logFile) {
        Remove-Item -Force $logFile
        Write-Host "cleaned: $logFile"
    }
    return
}

# --- 1. locate MSVC toolchain (vcvars64.bat) ---
if ($Vcvars) {
    $vcvars = $Vcvars
    if (-not (Test-Path $vcvars)) {
        throw "vcvars64.bat not found: $vcvars"
    }
    Write-Host "using specified toolchain: $vcvars"
} else {
    $candidates = @(
        'C:\Program Files\Microsoft Visual Studio\18\Professional\VC\Auxiliary\Build\vcvars64.bat'
        'C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvars64.bat'
        'C:\Program Files\Microsoft Visual Studio\18\BuildTools\VC\Auxiliary\Build\vcvars64.bat'
        'C:\Program Files\Microsoft Visual Studio\17\Professional\VC\Auxiliary\Build\vcvars64.bat'
        'C:\Program Files\Microsoft Visual Studio\17\Community\VC\Auxiliary\Build\vcvars64.bat'
        'C:\Program Files\Microsoft Visual Studio\17\BuildTools\VC\Auxiliary\Build\vcvars64.bat'
        'C:\Program Files (x86)\Microsoft Visual Studio\18\Professional\VC\Auxiliary\Build\vcvars64.bat'
        'C:\Program Files (x86)\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvars64.bat'
        'C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Auxiliary\Build\vcvars64.bat'
        'C:\Program Files (x86)\Microsoft Visual Studio\17\Professional\VC\Auxiliary\Build\vcvars64.bat'
        'C:\Program Files (x86)\Microsoft Visual Studio\17\Community\VC\Auxiliary\Build\vcvars64.bat'
        'C:\Program Files (x86)\Microsoft Visual Studio\17\BuildTools\VC\Auxiliary\Build\vcvars64.bat'
    )
    $vcvars = $null
    foreach ($c in $candidates) {
        if (Test-Path $c) {
            $vcvars = $c
            break
        }
    }
    if (-not $vcvars) {
        Write-Host 'ERROR: MSVC toolchain (vcvars64.bat) not found.' -ForegroundColor Red
        Write-Host 'Install VS 2022/2025 with "Desktop development with C++",' -ForegroundColor Red
        Write-Host 'or specify -Vcvars "path\to\vcvars64.bat".' -ForegroundColor Red
        Write-Host 'Checked paths:' -ForegroundColor Yellow
        foreach ($c in $candidates) { Write-Host "  - $c" -ForegroundColor Yellow }
        exit 1
    }
    Write-Host "found toolchain: $vcvars"
}

# --- 2. build C++ winmm.dll proxy ---
Write-Host '=== building C++ winmm.dll proxy ===' -ForegroundColor Cyan

# 构建前若产物已存在先删除，避免增量链接/锁定导致的陈旧产物。
if (Test-Path $cppTarget) {
    Remove-Item -Force $cppTarget
    Write-Host "removed existing: $cppTarget"
}

New-Item -ItemType Directory -Force -Path $objDir | Out-Null

$sources = @(
    'dllmain.cpp',
    'log.cpp',
    'window_controller.cpp'
) | ForEach-Object { '"' + (Join-Path $srcDir $_) + '"' }

$exportsHeader = Join-Path $srcDir 'winmm_exports.h'
if (-not (Test-Path $exportsHeader)) {
    throw 'winmm_exports.h missing; run tools\gen_exports.ps1 first.'
}

$clFlags = @(
    '/nologo'
    '/utf-8'
    '/std:c++17'
    '/W4'
    '/O2'
    '/MT'
    '/EHsc'
    '/DUNICODE'
    '/D_UNICODE'
    '/DWIN32_LEAN_AND_MEAN'
    '/Fo:"' + $objDir + '\\"'
) -join ' '

$linkFlags = @(
    '/nologo'
    '/DLL'
    '/MACHINE:X64'
    '/OPT:NOICF'
    '/OUT:"' + $cppTarget + '"'
    '/IMPLIB:"' + (Join-Path $objDir 'winmm.lib') + '"'
    'user32.lib'
    'shell32.lib'
    'kernel32.lib'
    'dwmapi.lib'
    'gdi32.lib'
    'dbghelp.lib'
) -join ' '

$cmd = "call `"$vcvars`" >nul 2>&1 && cl $clFlags $($sources -join ' ') /link $linkFlags"

$logFile = Join-Path $root 'make.log'
cmd /c "$cmd" 2>&1 | Tee-Object -FilePath $logFile

if (-not (Test-Path $cppTarget)) {
    Write-Host "C++ build failed, see: $logFile" -ForegroundColor Red
    exit 1
}
$cppSize = [math]::Round((Get-Item $cppTarget).Length / 1KB, 1)
Write-Host "C++ build succeeded -> $cppTarget ($cppSize KB)" -ForegroundColor Green
