#pragma once

// 手动维护的版本号（
#define LILITHWINDOWCAPTURE_VERSION_MAJOR 1
#define LILITHWINDOWCAPTURE_VERSION_MINOR 0
#define LILITHWINDOWCAPTURE_VERSION_PATCH 0
#define LILITHWINDOWCAPTURE_VERSION_WSTR L"1.0.0"
